- app/forms/decidim/participatory_documents/admin/document_form.rb
- app/packs/entrypoints/decidim_participatory_documents.js
- app/packs/entrypoints/decidim_participatory_documents.scss
- app/packs/stylesheets/decidim/participatory_documents/pdf_document.scss
- app/views/decidim/participatory_documents/documents/index.html.erb
- config/assets.rb
- spec/form/admin/document_form_spec.rb
- spec/system/index_participatory_documents_spec.rb
> Optional title and description

- app/controllers/decidim/participatory_documents/admin/application_controller.rb
- app/controllers/decidim/participatory_documents/admin/documents_controller.rb
- app/views/decidim/participatory_documents/admin/documents/_title.html.erb
- app/views/decidim/participatory_documents/admin/documents/edit.html.erb
- app/views/decidim/participatory_documents/admin/documents/edit_pdf.html.erb
- app/views/decidim/participatory_documents/admin/documents/index.html.erb
- app/views/decidim/participatory_documents/admin/documents/new.html.erb
- app/views/decidim/participatory_documents/admin/suggestions/index.html.erb
- spec/system/admin/admin_manages_participatory_documents_spec.rb
Add redirect to suggestions controller if the document is uploaded. 
Fixes: #41
> Redirect to suggestions controller in certain conditions

- .github/workflows/lint.yml
- .github/workflows/test.yml
- app/commands/decidim/participatory_documents/admin/answer_suggestion.rb
- app/controllers/decidim/participatory_documents/admin/suggestions_controller.rb
- app/forms/decidim/participatory_documents/admin/answer_suggestion_form.rb
- app/models/decidim/participatory_documents/suggestion.rb
- app/views/decidim/participatory_documents/admin/suggestions/show.html.erb
- config/locales/en.yml
- db/migrate/20221115233023_create_decidim_participatory_documents_suggestions.rb
- lib/decidim/participatory_documents/admin_engine.rb
- lib/decidim/participatory_documents/component.rb
- spec/commands/decidim/participatory_documents/admin/answer_suggestion_spec.rb
- spec/commands/decidim/participatory_documents/admin/destroy_section_spec.rb
- spec/system/admin/admin_manages_suggestions_spec.rb
> Add answer suggestion controller

- app/controllers/decidim/participatory_documents/documents_controller.rb
- config/locales/en.yml
- spec/system/index_participatory_documents_spec.rb
> Handle missing document in front interface

- app/controllers/decidim/participatory_documents/admin/annotations_controller.rb
- app/controllers/decidim/participatory_documents/admin/application_controller.rb
- app/controllers/decidim/participatory_documents/admin/documents_controller.rb
- app/controllers/decidim/participatory_documents/admin/sections_controller.rb
- app/controllers/decidim/participatory_documents/admin/suggestions_controller.rb
Removed duplicated code in the admin controllers
> Extract the document method in Admin Application controller

- app/cells/decidim/participatory_documents/suggestion/show.erb
> Remove the status badge

- app/cells/decidim/participatory_documents/suggestion_cell.rb
- app/commands/decidim/participatory_documents/admin/answer_suggestion.rb
- app/forms/decidim/participatory_documents/admin/answer_suggestion_form.rb
- app/views/decidim/participatory_documents/admin/suggestions/show.html.erb
- config/locales/en.yml
- db/migrate/20221115233023_create_decidim_participatory_documents_suggestions.rb
- lib/decidim/participatory_documents/test/factories.rb
- spec/commands/decidim/participatory_documents/admin/answer_suggestion_spec.rb
- spec/system/admin/admin_manages_suggestions_spec.rb
- spec/system/user_interacts_with_pdf_viewer_spec.rb
> Fix: Default answers to "not published"

- app/commands/decidim/participatory_documents/admin/create_suggestion_note.rb
- app/controllers/decidim/participatory_documents/admin/suggestion_notes_controller.rb
- app/controllers/decidim/participatory_documents/admin/suggestions_controller.rb
- app/forms/decidim/participatory_documents/admin/suggestion_note_form.rb
- app/models/decidim/participatory_documents/suggestion.rb
- app/models/decidim/participatory_documents/suggestion_note.rb
- app/presenters/decidim/participatory_documents/admin_log/suggestion_note_presenter.rb
- app/views/decidim/participatory_documents/admin/suggestion_notes/_form.html.erb
- app/views/decidim/participatory_documents/admin/suggestion_notes/_suggestion_notes.html.erb
- app/views/decidim/participatory_documents/admin/suggestions/show.html.erb
- config/locales/en.yml
- db/migrate/20221115233024_create_decidim_participatory_documents_suggestion_notes.rb
- lib/decidim/participatory_documents/admin_engine.rb
- lib/decidim/participatory_documents/test/factories.rb
- spec/forms/decidim/participatory_documents/admin/suggestion_note_form_spec.rb
- spec/models/decidim/participatory_documents/suggestion_note_spec.rb
- spec/system/admin/index_suggestion_notes_spec.rb
> Add private notes

- app/permissions/decidim/participatory_documents/admin/permissions.rb
- spec/permissions/decidim/participatory_documents/admin/permissions_spec.rb
> Add Permission spec

- app/models/concerns/decidim/participatory_documents/participatory_space_user_role_override.rb
- app/views/decidim/participatory_documents/admin/suggestions/index.html.erb
- lib/decidim/participatory_documents/engine.rb
- spec/models/decidim/participatory_documents/valuation_assignment_spec.rb
- spec/system/admin/admin_manages_suggestion_valuators_spec.rb
> Show name of valuators in the list

- app/models/decidim/participatory_documents/suggestion.rb
- app/views/decidim/participatory_documents/admin/suggestions/index.html.erb
- config/locales/en.yml
- spec/system/admin/admin_manages_suggestions_spec.rb
> Name of the author in the list of suggestions

- app/controllers/decidim/participatory_documents/admin/suggestions_controller.rb
- app/models/decidim/participatory_documents/suggestion.rb
- config/locales/en.yml
- spec/system/admin/admin_manages_suggestions_spec.rb
> Add Author and Section filters

- app/models/decidim/participatory_documents/suggestion.rb
- app/views/decidim/participatory_documents/admin/suggestions/index.html.erb
- config/locales/en.yml
- lib/decidim/participatory_documents/test/factories.rb
- spec/system/admin/admin_manages_suggestions_spec.rb
- spec/system/admin/index_suggestion_notes_spec.rb
> Add answer state in admin listing

- app/commands/decidim/participatory_documents/admin/answer_suggestion.rb
- app/commands/decidim/participatory_documents/admin/notify_suggestion_answer.rb
- app/commands/decidim/participatory_documents/admin/publish_answers.rb
- app/controllers/decidim/participatory_documents/admin/suggestions_controller.rb
- app/models/concerns/decidim/participatory_documents/valuator_override.rb
- app/models/decidim/participatory_documents/suggestion.rb
- app/packs/src/decidim/participatory_documents/suggestions_admin.js
- app/permissions/decidim/participatory_documents/admin/permissions.rb
- app/views/decidim/participatory_documents/admin/suggestions/_bulk-actions.html.erb
- app/views/decidim/participatory_documents/admin/suggestions/_js-callout.html.erb
- app/views/decidim/participatory_documents/admin/suggestions/_suggestion.html.erb
- app/views/decidim/participatory_documents/admin/suggestions/bulk_actions/_dropdown.html.erb
- app/views/decidim/participatory_documents/admin/suggestions/bulk_actions/_publish_answers.html.erb
- app/views/decidim/participatory_documents/admin/suggestions/index.html.erb
- app/views/decidim/participatory_documents/admin/suggestions/publish_answers.js.erb
- config/locales/en.yml
- lib/decidim/participatory_documents/admin_engine.rb
- lib/decidim/participatory_documents/engine.rb
- lib/decidim/participatory_documents/test/factories.rb
- spec/commands/decidim/participatory_documents/admin/answer_suggestion_spec.rb
- spec/permissions/decidim/participatory_documents/admin/permissions_spec.rb
- spec/system/admin/admin_manages_suggestions_spec.rb
- spec/system/admin/index_suggestion_notes_spec.rb
> Add bulk answer suggestion functionality

- app/controllers/decidim/participatory_documents/admin/documents_controller.rb
- app/models/decidim/participatory_documents/suggestion.rb
- app/serializers/decidim/participatory_documents/suggestion_serializer.rb
- app/views/decidim/admin/exports/_dropdown.html.erb
- app/views/decidim/participatory_documents/admin/suggestions/_bulk-actions.html.erb
- config/locales/en.yml
- lib/decidim/participatory_documents/component.rb
- spec/serializers/suggestion_serialiser_spec.rb
- spec/system/admin/admin_manages_suggestions_spec.rb
> Export suggestions

- app/controllers/decidim/participatory_documents/admin/documents_controller.rb
- spec/system/admin/admin_manages_participatory_documents_spec.rb
fixes stadtluzern/decidim-pdf-consultations/issues/43
> Jump directly to the "edit the participatory document"

- app/packs/images/fullscreen_exit.svg
- app/packs/src/decidim/participatory_documents/global.js
- app/packs/stylesheets/decidim/participatory_documents/pdf/tweaks.scss
- app/views/decidim/participatory_documents/documents/_pdfjs_base.html.erb
- config/locales/en.yml
- spec/system/index_participatory_documents_spec.rb
fixes stadtluzern/decidim-pdf-consultations/issues/41
> change exit fullscreen button

- app/serializers/decidim/participatory_documents/suggestion_serializer.rb
- lib/decidim/participatory_documents.rb
- package-lock.json
- spec/serializers/suggestion_serialiser_spec.rb
fixes stadtluzern/decidim-pdf-consultations/issues/40
> add the answer text to the export file

- app/cells/decidim/participatory_documents/edit_suggestion_note_modal/show.erb
- app/cells/decidim/participatory_documents/edit_suggestion_note_modal_cell.rb
- app/commands/decidim/participatory_documents/admin/update_suggestion_note.rb
- app/controllers/decidim/participatory_documents/admin/suggestion_notes_controller.rb
- app/permissions/decidim/participatory_documents/admin/permissions.rb
- app/views/decidim/participatory_documents/admin/suggestion_notes/_editing_suggestion_note.html.erb
- app/views/decidim/participatory_documents/admin/suggestion_notes/_suggestion_notes.html.erb
- config/locales/en.yml
- lib/decidim/participatory_documents/admin_engine.rb
- spec/cells/decidim/participatory_documents/admin/edit_suggestion_note_modal_cell_spec.rb
- spec/commands/decidim/participatory_documents/admin/update_suggestion_note_spec.rb
- spec/permissions/decidim/participatory_documents/admin/permissions_spec.rb
- spec/system/admin/edit_suggestion_notes_spec.rb
fixes https://github.com/stadtluzern/decidim-pdf-consultations/issues/35
> Improve suggestion notes

- app/cells/decidim/participatory_documents/suggestion/show.erb
- app/cells/decidim/participatory_documents/suggestion_cell.rb
- app/commands/decidim/participatory_documents/create_suggestion.rb
- app/controllers/decidim/participatory_documents/document_suggestions_controller.rb
- app/controllers/decidim/participatory_documents/section_suggestions_controller.rb
- app/forms/decidim/participatory_documents/suggestion_form.rb
- app/helpers/decidim/participatory_documents/admin/suggestion_helper.rb
- app/models/decidim/participatory_documents/suggestion.rb
- app/packs/src/decidim/participatory_documents/pdf/suggestion_form.js
- app/packs/stylesheets/decidim/participatory_documents/pdf/modals.scss
- app/views/decidim/participatory_documents/admin/suggestions/_suggestion.html.erb
- app/views/decidim/participatory_documents/admin/suggestions/show.html.erb
- app/views/decidim/participatory_documents/document_suggestions/_form.html.erb
- config/locales/en.yml
- spec/forms/decidim/participatory_documents/suggestion_form_spec.rb
- spec/helpers/decidim/participatory_documents/admin/suggestion_helper_spec.rb
- spec/system/admin/admin_manages_suggestions_spec.rb
- spec/system/user_interacts_with_pdf_viewer_spec.rb
fixes stadtluzern/decidim-pdf-consultations/issues/37
> Upload suggestions to global

- app/packs/entrypoints/decidim_participatory_documents_editor.scss
- app/packs/src/decidim/participatory_documents/global.js
- app/packs/src/decidim/participatory_documents/pdf/box.js
- app/packs/src/decidim/participatory_documents/pdf/polygon_editor.js
- app/packs/src/decidim/participatory_documents/pdf/polygon_viewer.js
- app/packs/src/decidim/participatory_documents/pdf_admin.js
- app/packs/src/decidim/participatory_documents/pdf_notifications.js
- app/packs/stylesheets/decidim/participatory_documents/pdf/admin_polygons.scss
- app/packs/stylesheets/decidim/participatory_documents/pdf/admin_tweaks.scss
- app/packs/stylesheets/decidim/participatory_documents/pdf/tweaks.scss
fixes https://github.com/stadtluzern/decidim-pdf-consultations/issues/46
supersedes #89
> Enable links on PDFs for public viewer

- app/forms/decidim/participatory_documents/suggestion_form.rb
- config/locales/en.yml
- spec/system/user_interacts_with_pdf_viewer_spec.rb
> Fix translated body

- .github/workflows/test.yml
- Gemfile.lock
- app/controllers/decidim/participatory_documents/admin/suggestions_controller.rb
- app/controllers/decidim/participatory_documents/admin/valuation_assignments_controller.rb
- app/permissions/decidim/participatory_documents/admin/permissions.rb
- app/views/decidim/participatory_documents/admin/suggestions/_add_valuators.html.erb
- app/views/decidim/participatory_documents/admin/suggestions/_valuators.html.erb
- spec/controllers/decidim/participatory_documents/admin/valuation_assignments_controller_spec.rb
- spec/permissions/decidim/participatory_documents/admin/permissions_spec.rb
- spec/system/admin/admin_manages_suggestion_valuators_spec.rb
- spec/system/admin/admin_manages_suggestions_spec.rb
Valuator can add valuators only if he is a suggestion valuator himself
> Fix permissions for the assignment of valuator
